SELECT SYSDATE AS NOW
,SYSDATE-1 AS YESTERDAY
, SYSDATE+1 AS TOMORROW
FROM EMP;

SELECT SYSDATE, ADD_MONTHS(SYSDATE,3)
FROM DUAL;

SELECT EMPNO, ENAME, HIREDATE,
ADD_MONTHS(HIREDATE, 12*20) AS WORK10YEAR
FROM EMP;

SELECT EMPNO, ENAME,HIREDATE,SYSDATE 
FROM EMP
WHERE ADD_MONTHS(HIREDATE, 12*40) > SYSDATE;

SELECT SYSDATE, ROUND(SYSDATE, 'CC') AS FORMAT_CC,
ROUND(SYSDATE, 'YYYY') AS FORMAT_YYYY,
ROUND(SYSDATE, 'Q') AS FORMAT_Q,
ROUND(SYSDATE, 'DDD') AS FORMAT_DDD,
ROUND(SYSDATE, 'HH') AS FORMAT_HH
FROM DUAL;

SELECT EMPNO, ENAME, EMPNO + '500' FROM EMP 
WHERE ENAME = 'SCOTT';

-- SELECT 1300 - '1500', '1300' + 1500 FROM DUAL;

SELECT TO_NUMBER('1,500', '9,999') - 1300 - FROM DUAL; 