SELECT SYSDATE 
, TO-CHAR(SYSDATE, 'HH24:MI:SS') AS HH24MISS
, TO-CHAR(SYSDATE, 'HH12:MI:SS AM') AS HH24MISS_AM
, TO-CHAR(SYSDATE, 'HH24:MI:SS P.M.') AS HH24MISS_PM
FROM DUAL;

SELECT TO_NUMBER('3,300', '999,999') - TO_NUMBER('1,100','999,999')
	FROM DUAL;

SELECT TO_DATE('2023/02/15', 'YYYY/MM/DD') AS TODATE1
		,TO_DATE('20150101', 'YYYY-MM-DD') AS TODATE2
FROM DUAL;

SELECT SUM(COMM) FROM EMP;

SELECT EMPNO, ENAME, COMMENT
,NVL2(COMM, 'O','X') 
,NVL2(COMM, SAL*12 + COMM, SAL*12) AS ANNSAL
FROM EMP;

SELECT *
FROM emp, DEPT
WHERE emp.DEPTNO = dept.DEPTNO
ORDER BY empno;

SELECT *
FROM emp e JOIN DEPT D
ON (e.DEPTNO = d.DEPTNO)
ORDER BY EMPNO ;

SELECT *
FROM emp e JOIN dept D using(DEPTNO)
ORDER BY e.EMPNO ;

SELECT E.EMPNO, E.ENAME, E.SAL, D.DEPTNO, D.DNAME, D.LOC
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO 
	AND SAL<=2000;
